Figaro.require_keys(
                    "DB_HOST",
                    "DB_USERNAME",
                    "DB_PASSWORD",
                    "AUTH_USERNAME",
                    "AUTH_PASSWORD",
                    "REDIRECT_URI",
                    "SECURE_KEY",
                    "GOOGLE_EMAIL",
                    "GOOGLE_PASSWORD",
                    "ROOT_URL"
                   )
